### ISSUE TITLE
SigVerify only supports 255 characters?

### ISSUE THREAD

**Issue by lf94** [trezor/trezor-wallet#580]
We ([Bity](https://bity.com)) are using signatures as a way for users to prove ownership, but in order to do this, we ask them to sign a fairly lengthy message.

The issue with this is that Trezor's web interface doesn't support past 255 characters.

I am guessing the assumption is the user of the web interface is expected to input a hashed message already, versus hashing directly in the web interface.

In any case - we request if this limitation / bad UX can be corrected. We would love to support Trezor.

**Comment by prusnak** [comment]
We support signing only messages shorter than 256 bytes. I suggest you fix your ownership proof to be shorter than 256 byteds.

**Comment by lf94** [comment]
@prusnak I take it my assumption is incorrect, and that Trezor actually does expect regular prose to be input?

**Comment by lf94** [comment]
Thanks @prusnak . I was hoping for a small explanation why, but with some digging I think I've found out. I've pasted what I've found below for others who find themselves hitting the same problem.

> we request if this limitation / bad UX can be corrected.

I regret my wording here. I meant no offense. It just seems like a big limitation when it comes to signing messages. From what I understand this is because it's more tamper proof (?) to send over the entire message / bytes unmodified, than to perform any work in the web client.

The only solution that comes to mind is requesting users sign a hash of a message, since it is fixed length and should always fit within the 256 byte limit.

Other than that: is there a reason why this limit can't be raised to what's defined in the protobuf options file?

----

## trezor-connect

`src/js/core/methods/SignMessage.js: run()`

Takes care of passing the message from a client to the device. 

`src/js/device/DeviceCommands.js: signMessage()`

It passes the type `SignMessage` and returns the type `MessageSignature` to `typedCall`.

`typedCall` drills down to `transport.call` which is defined in `trezor-link`.

## trezor-link

`src/lowlevel/send.js: class BuiltMessage`

transport.call builds and sends off a protobuf message.

This protobuf type is defined in `trezor-firmware`.

## trezor-firmware

`legacy/src/firmware/protob/messages-bitcoin.options`

```
SignMessage.address_n                                       max_count:8
SignMessage.message                                         max_size:1024
SignMessage.coin_name                                       max_size:21
```

**Comment by prusnak** [comment]
Most of the software wallets contain a bug which makes it impossible to sign/verify the message longer than 255 bytes. We fixed that in our code, but I **strongly** discourage anyone from using longer messages than this limit, because you will run into problems with other wallets.

**Comment by lf94** [comment]
@prusnak ah ok! This is very good information to know. Thank you again :slightly_smiling_face:

**Comment by dantuluri** [comment]
Any update on this? Trezor still doesn't support over 255 characters and Bity asks for a fairly lengthy message @lf94 .

**Comment by lf94** [comment]
@dantuluri from what I can see, there are only two ways forward:

1. Trezor removes this limitation.
2. Bity hashes what we ask the user to sign, and they sign the hash.

There are issues with both of these ways forward.

Research will have to be done, into determining exactly how many other wallets have this limitation, in order to convince Trezor maintainers to remove or second best, increase this limit.

The issue with the second way forward is Bity cannot expect users to understand what a hash is, and thus they would have no idea what they are signing. Just saying "this string is unique to this message we want you to sign" is not enough.

So that's where we're at...I'm a Trezor user myself, I love my Trezor one, and it makes me sad I cannot use it for Bitcoin exchanges. Luckily, I can use my Trezor with Bity during Ethereum exchanges through Metamask.

We are completely open to ideas on how to solve this. It hurts everyone. What is even crazier, is that some hardware wallets don't support signing *at all*... Let's show everyone how world class Trezor is.

**Comment by prusnak** [comment]
Okay, let's change the limitation to 1024 in the UI. This should be enough for everyone

**Comment by lf94** [comment]
Haha, this is a nice surprise :slightly_smiling_face: !

I think 1024 would be fine too. The largest message Bity asks users to sign is the following:

```
This message is part of the process of placing an exchange order on bity.com. To proceed, Bity is required to verify that you own the destination crypto address. By signing this message with your wallet, you are confirming 1) that you are the sole owner of the crypto address below and 2) that you will be sending your own funds to Bity. If you did not initiate this process yourself, do not sign this message.

Your order id: {{ order_id }}
{{# full_name? }}Your full name: {{ full_name }}
{{/ full_name? }}Your IBAN: {{ iban }}
Your crypto address: {{ crypto_address }}
Your crypto address type: {{ crypto_address_type }}
```

Which is ~600 characters give or take the templated values.

The beginning header is extremely important, because when the user signs it (along with the rest of the information), it tells us they accept the conditions. (You may already know this, but could be useful to others wondering "why can't the big message be left outside of the message to sign?")

Anyway, while I think it *would* be better to provide double this space (2048) to greatly minimize failure, I'll take what I can get :slightly_smiling_face: 

Thanks a lot @prusnak !

**Comment by lf94** [comment]
@prusnak , how long until we can expect this change to land in https://beta-wallet.trezor.io or https://wallet.trezor.io ? I would like to finally integrate Trezor signing support into our client but can't until users can actually sign :smile: I even checked https://beta-wallet.trezor.io/next/ but the change wasn't there either. Thank you!
